moengage/React-Native

- sdk/cards/CHANGELOG.md
- sdk/cards/ReactNativeMoEngageCards.podspec
- sdk/core/CHANGELOG.md
- sdk/core/ReactNativeMoEngage.podspec
- sdk/geofence/CHANGELOG.md
- sdk/geofence/ReactNativeMoEngageGeofence.podspec
- sdk/inbox/CHANGELOG.md
- sdk/inbox/ReactNativeMoEngageInbox.podspec
> Updated to  iOS 9.17.0

- .github/scripts/release.sh
- .github/workflows/release.yml
- SampleApp/PushNotification.js
https://moengagetrial.atlassian.net/browse/MOEN-30729
Release Script Changes
> MOEN-30729: Release Script Changes

- sdk/cards/CHANGELOG.md
- sdk/cards/package.json
- sdk/core/CHANGELOG.md
- sdk/core/package.json
- sdk/geofence/CHANGELOG.md
- sdk/geofence/package.json
- sdk/inbox/CHANGELOG.md
- sdk/inbox/package.json
https://moengagetrial.atlassian.net/browse/MOEN-31372
package version update
> Package version update

- sdk/cards/CHANGELOG.md
- sdk/core/CHANGELOG.md
- sdk/geofence/CHANGELOG.md
- sdk/inbox/CHANGELOG.md
> date updated in changelog

- SampleApp/package.json
- sdk/cards/CHANGELOG.md
- sdk/cards/ReactNativeMoEngageCards.podspec
- sdk/core/CHANGELOG.md
- sdk/core/ReactNativeMoEngage.podspec
- sdk/geofence/CHANGELOG.md
- sdk/geofence/ReactNativeMoEngageGeofence.podspec
- sdk/inbox/CHANGELOG.md
- sdk/inbox/ReactNativeMoEngageInbox.podspec
https://moengagetrial.atlassian.net/browse/MOEN-31558
[Production][React][iOS]: Pod install fails with latest react-native-moengage package 10.0.0
> Pod install fails with latest react-native-moengage package 10.0.0

- SampleApp/package.json
- sdk/cards/CHANGELOG.md
- sdk/cards/android/src/main/java/com/moengage/react/cards/MoEngageCardsPackage.kt
- sdk/core/CHANGELOG.md
- sdk/core/android/src/main/java/com/moengage/react/MoEReactPackage.kt
- sdk/geofence/CHANGELOG.md
- sdk/geofence/android/src/main/java/com/moengage/react/geofence/MoengageGeofencePackage.kt
- sdk/inbox/CHANGELOG.md
- sdk/inbox/android/src/main/java/com/moengage/react/inbox/MoengageInboxPackage.kt
https://moengagetrial.atlassian.net/browse/MOEN-31593
Adding backward compatibility support for react-native version below 0.73
> MOEN-31593: Backward compatibility support for react-native version below 0.73

- sdk/cards/CHANGELOG.md
- sdk/cards/package.json
- sdk/core/CHANGELOG.md
- sdk/core/package.json
- sdk/geofence/CHANGELOG.md
- sdk/geofence/package.json
- sdk/inbox/CHANGELOG.md
- sdk/inbox/package.json
https://moengagetrial.atlassian.net/browse/MOEN-31628
Release: Core -10.0.1,inbox-4.0.1, geofence-5.0.1, cards-3.0.1
> Release: Core -10.0.1,inbox-4.0.1, geofence-5.0.1, cards-3.0.1

- SampleApp/android/settings.gradle
- sdk/core/CHANGELOG.md
- sdk/core/android/build.gradle
- sdk/core/package.json
NA
- `moe-android-sdk` version updated to `13.01.00`
- `inapp` version updated to `8.3.0`
> MOEN-31732: Release: Core 10.1.0

- SampleApp/TrackEvent.js
- SampleApp/UserAttribute.js
- sdk/core/CHANGELOG.md
- sdk/core/android/build.gradle
- sdk/core/src/index.ts
- sdk/core/src/models/MoEProperties.ts
- sdk/core/src/models/MoESupportedAttributes.ts
- sdk/core/src/utils/MoEJsonBuilder.ts
https://moengagetrial.atlassian.net/browse/MOEN-31743
Support for JSONArray and JSONObject in Attribute
- Change the `plugin-base` & `moe-android-sdk` version before merge
> MOEN-31743: Support for JSONArray and JSONObject in Attribute

- sdk/cards/android/build.gradle
- sdk/core/CHANGELOG.md
- sdk/core/android/build.gradle
- sdk/geofence/CHANGELOG.md
- sdk/geofence/android/build.gradle
- sdk/inbox/CHANGELOG.md
- sdk/inbox/android/build.gradle
https://moengagetrial.atlassian.net/browse/MOEN-32361
- moe-android-sdk: 13.02.00
- inapp: 8.3.1
- inbox-core: 3.0.2
- geofence: 4.0.2
> MOEN-32361: Release Version Update

- SampleApp/android/app/build.gradle
- SampleApp/android/build.gradle
- SampleApp/android/gradle/wrapper/gradle-wrapper.properties
- SampleApp/android/settings.gradle
- sdk/cards/CHANGELOG.md
- sdk/cards/android/build.gradle
- sdk/cards/android/gradle/wrapper/gradle-wrapper.properties
- sdk/core/CHANGELOG.md
- sdk/core/android/build.gradle
- sdk/core/android/gradle/wrapper/gradle-wrapper.properties
- sdk/geofence/CHANGELOG.md
- sdk/geofence/android/build.gradle
- sdk/geofence/android/gradle/wrapper/gradle-wrapper.properties
- sdk/inbox/CHANGELOG.md
- sdk/inbox/android/build.gradle
- sdk/inbox/android/gradle/wrapper/gradle-wrapper.properties
https://moengagetrial.atlassian.net/browse/MOEN-33207
- `moe-android-sdk` version updated to `13.03.00`
- `inapp` version updated to `8.4.1`
- `cards-core` version updated to `2.1.0`
- `inbox-core` version updated to `3.1.0`
- `geofence` version updated to `4.1.0`
- Added support for AGP `8.4.0` and above
- Kotlin version updated to `1.9.23`
- Compile SDK version updated to `34`
> MOEN-33207: AGP + Kotlin + Compile SDK Version update

- sdk/cards/CHANGELOG.md
- sdk/cards/package.json
- sdk/cards/src/internal/MoEngageCardHandler.ts
- sdk/core/CHANGELOG.md
- sdk/core/package.json
- sdk/core/src/index.ts
- sdk/core/src/moeParser/MoEInAppParser.ts
- sdk/core/src/moeParser/MoEngagePayloadParser.ts
- sdk/core/src/utils/MoEJsonBuilder.ts
- sdk/geofence/CHANGELOG.md
- sdk/geofence/package.json
- sdk/geofence/src/index.ts
- sdk/inbox/CHANGELOG.md
- sdk/inbox/package.json
https://moengagetrial.atlassian.net/browse/MOEN-32740
Fixing the warning produced by `tsc --noEmit`
> MOEN-32740: Typescript warning fixes

- sdk/cards/CHANGELOG.md
- sdk/cards/ReactNativeMoEngageCards.podspec
- sdk/core/CHANGELOG.md
- sdk/core/ReactNativeMoEngage.podspec
- sdk/geofence/CHANGELOG.md
- sdk/geofence/ReactNativeMoEngageGeofence.podspec
- sdk/inbox/CHANGELOG.md
- sdk/inbox/ReactNativeMoEngageInbox.podspec
https://moengagetrial.atlassian.net/browse/MOEN-33417
Pinned iOS dependency version
> MOEN-33417: Pinned iOS dependency version

- sdk/cards/CHANGELOG.md
- sdk/cards/package.json
- sdk/core/CHANGELOG.md
- sdk/core/package.json
- sdk/geofence/CHANGELOG.md
- sdk/geofence/package.json
- sdk/inbox/CHANGELOG.md
- sdk/inbox/package.json
https://moengagetrial.atlassian.net/browse/MOEN-33542
version update
> MOEN-33542: version update

- SampleApp/PushNotification.js
- sdk/core/CHANGELOG.md
- sdk/core/iOS/MoEReactBridge/MoEReactBridge.mm
- sdk/core/iOS/MoEReactBridge/MoEReactNativeHandler.h
- sdk/core/iOS/MoEReactBridge/MoEReactNativeHandler.m
- sdk/core/src/NativeMoEngage.ts
- sdk/core/src/index.ts
https://moengagetrial.atlassian.net/browse/MOEN-34369
Register for provisional pusn
> MOEN-34369: Register for provisional pusn

- sdk/cards/CHANGELOG.md
- sdk/cards/ReactNativeMoEngageCards.podspec
- sdk/core/CHANGELOG.md
- sdk/core/ReactNativeMoEngage.podspec
- sdk/core/iOS/MoEReactBridge/MoEReactNativeHandler.m
- sdk/geofence/CHANGELOG.md
- sdk/geofence/ReactNativeMoEngageGeofence.podspec
- sdk/inbox/CHANGELOG.md
- sdk/inbox/ReactNativeMoEngageInbox.podspec
https://moengagetrial.atlassian.net/browse/MOEN-34386
Updated iOS pluginbase dependency
> MOEN-34386: Updated iOS pluginbase dependency

- sdk/cards/android/build.gradle
- sdk/core/android/build.gradle
https://moengagetrial.atlassian.net/browse/MOEN-34540
Android dependency versions update
> MOEN-34540: Android dependency versions update

- sdk/core/CHANGELOG.md
- sdk/core/src/models/MoEInAppRules.ts
- sdk/core/src/moeParser/MoEInAppParser.ts
https://moengagetrial.atlassian.net/browse/MOEN-34834
Fixing the lint issue for `getMoEInAppRules` with `noImplicitAny` as false in tsconfig file
> MOEN-34834: Lint Issue Fix

- sdk/cards/CHANGELOG.md
- sdk/cards/ReactNativeMoEngageCards.podspec
- sdk/core/CHANGELOG.md
- sdk/core/ReactNativeMoEngage.podspec
- sdk/geofence/CHANGELOG.md
- sdk/geofence/ReactNativeMoEngageGeofence.podspec
- sdk/inbox/CHANGELOG.md
- sdk/inbox/ReactNativeMoEngageInbox.podspec
https://moengagetrial.atlassian.net/browse/MOEN-35335
Updated dependency
> MOEN-35335: Updated dependency

- SampleApp/ios/Podfile
- SampleApp/ios/SampleApp/AppDelegate.mm
- sdk/core/iOS/MoEReactBridge/MoEReactBridge.h
- sdk/core/iOS/MoEReactBridge/MoEReactBridge.mm
- sdk/core/iOS/MoEReactBridge/MoEReactEventDispatcher.h
- sdk/core/iOS/MoEReactBridge/MoEReactNativeHandler.h
- sdk/core/iOS/MoEReactBridge/MoEReactNativeHandler.m
- sdk/core/iOS/MoEReactBridge/MoEngageInitializer.m
https://moengagetrial.atlassian.net/browse/MOEN-36125
React version 0.76 update iOS.
> MOEN-36125: React version 0.76 update iOS.

- sdk/core/CHANGELOG.md
- sdk/core/package.json
> MOEN-36192: Updated version and changelog

- SampleApp/android/settings.gradle
- sdk/cards/CHANGELOG.md
- sdk/cards/ReactNativeMoEngageCards.podspec
- sdk/cards/android/build.gradle
- sdk/cards/package.json
- sdk/core/CHANGELOG.md
- sdk/core/ReactNativeMoEngage.podspec
- sdk/core/android/build.gradle
- sdk/core/package.json
- sdk/geofence/CHANGELOG.md
- sdk/geofence/ReactNativeMoEngageGeofence.podspec
- sdk/geofence/android/build.gradle
- sdk/geofence/package.json
- sdk/inbox/CHANGELOG.md
- sdk/inbox/ReactNativeMoEngageInbox.podspec
- sdk/inbox/android/build.gradle
- sdk/inbox/package.json
https://moengagetrial.atlassian.net/browse/MOEN-36447
Release core-v11.1.3, inbox-v5.0.3, cards-v5.0.2, goefence-v6.0.3
> MOEN-36447: Release core-v11.1.3, inbox-v5.0.3, cards-v5.0.2, goefence-v6.0.3

- .github/scripts/release.main.kts
- .github/workflows/release.yml
https://moengagetrial.atlassian.net/browse/MOEN-36520
Adding support for release creation
> MOEN-36520: Adding support for release creation

- SampleApp/ios/Podfile
- sdk/cards/CHANGELOG.md
- sdk/cards/ReactNativeMoEngageCards.podspec
- sdk/core/CHANGELOG.md
- sdk/core/ReactNativeMoEngage.podspec
- sdk/geofence/CHANGELOG.md
- sdk/geofence/ReactNativeMoEngageGeofence.podspec
- sdk/inbox/CHANGELOG.md
- sdk/inbox/ReactNativeMoEngageInbox.podspec
https://moengagetrial.atlassian.net/browse/SUP-24299
https://moengagetrial.atlassian.net/browse/MOEN-36975
> MOEN-36975: Fix iOS build when `use_frameworks` enabled in `Podfile`

- sdk/core/CHANGELOG.md
- sdk/core/android/src/oldarch/com/moengage/react/MoEReactBridge.kt
https://moengagetrial.atlassian.net/browse/MOEN-37069
Multiple Self Handler InApp not working in old architecture
> MOEN-37069: Multiple Self Handler InApp not working in old architecture

- .github/scripts/verify-plugins.main.kts
- .github/workflows/pull_request_verification.yml
- RELEASING.md
https://moengagetrial.atlassian.net/browse/MOEN-36685
Making Verify Android & iOS Parallel Job
> MOEN-36685: CI + CD Improvements

- SampleApp/android/build.gradle
- SampleApp/android/gradle/wrapper/gradle-wrapper.properties
- sdk/cards/CHANGELOG.md
- sdk/cards/android/build.gradle
- sdk/cards/android/gradle/wrapper/gradle-wrapper.properties
- sdk/core/CHANGELOG.md
- sdk/core/android/build.gradle
- sdk/core/android/gradle/wrapper/gradle-wrapper.properties
- sdk/geofence/CHANGELOG.md
- sdk/geofence/android/build.gradle
- sdk/geofence/android/gradle/wrapper/gradle-wrapper.properties
- sdk/inbox/CHANGELOG.md
- sdk/inbox/android/build.gradle
- sdk/inbox/android/gradle/wrapper/gradle-wrapper.properties
https://moengagetrial.atlassian.net/browse/MOEN-36211
AGP Version updated to 8.7.3
> MOEN-36211: AGP Version update from `8.4.0` to `8.7.3`

- SampleApp/android/app/build.gradle
- SampleApp/android/build.gradle
- SampleApp/android/settings.gradle
- sdk/cards/CHANGELOG.md
- sdk/cards/android/build.gradle
- sdk/core/CHANGELOG.md
- sdk/core/android/build.gradle
- sdk/core/android/src/main/java/com/moengage/react/MoEInitializer.kt
- sdk/geofence/CHANGELOG.md
- sdk/geofence/android/build.gradle
- sdk/inbox/CHANGELOG.md
- sdk/inbox/android/build.gradle
https://moengagetrial.atlassian.net/browse/MOEN-37104
https://moengagetrial.atlassian.net/browse/MOEN-37105
1. Target SDK Updated to 35
2. Min SDK Updated to 23
> MOEN-37105: [Major Version] Updating Min SDK & Target SDK Version

- SampleApp/android/app/build.gradle
- SampleApp/android/build.gradle
- SampleApp/android/settings.gradle
- sdk/cards/CHANGELOG.md
- sdk/cards/android/build.gradle
- sdk/core/CHANGELOG.md
- sdk/core/android/build.gradle
- sdk/core/android/src/main/java/com/moengage/react/MoEInitializer.kt
- sdk/geofence/CHANGELOG.md
- sdk/geofence/android/build.gradle
- sdk/inbox/CHANGELOG.md
- sdk/inbox/android/build.gradle
Major Version:
https://moengagetrial.atlassian.net/browse/MOEN-37104
https://moengagetrial.atlassian.net/browse/MOEN-37105
Simplifying InApp:
https://moengagetrial.atlassian.net/browse/MOEN-38391
> MOEN-37105: Updating Min SDK & Target SDK Version (#52)

- SampleApp/ios/Podfile
- sdk/cards/CHANGELOG.md
- sdk/cards/ReactNativeMoEngageCards.podspec
- sdk/core/CHANGELOG.md
- sdk/core/ReactNativeMoEngage.podspec
- sdk/core/iOS/MoEReactBridge/MoEngageInitializer.m
- sdk/core/iOS/MoEReactBridge/MoEngageReactSDKInitializationConfig.m
- sdk/geofence/CHANGELOG.md
- sdk/geofence/ReactNativeMoEngageGeofence.podspec
- sdk/inbox/CHANGELOG.md
- sdk/inbox/ReactNativeMoEngageInbox.podspec
> MOEN-38539: Updated deployment target to 13

- SampleApp/android/settings.gradle
- sdk/cards/android/build.gradle
- sdk/core/android/build.gradle
- sdk/geofence/android/build.gradle
https://moengagetrial.atlassian.net/browse/MOEN-38803
Accessibility cards
> MOEN-38803: Accesibility in Cards

- SampleApp/android/settings.gradle
- SampleApp/src/CardsHelper.ts
- sdk/cards/CHANGELOG.md
- sdk/cards/ReactNativeMoEngageCards.podspec
- sdk/cards/android/build.gradle
- sdk/cards/android/src/main/java/com/moengage/react/cards/MoEngageCardsBridgeHandler.kt
- sdk/cards/src/internal/MoEngageCardHandler.ts
- sdk/cards/src/internal/utils/JsonToModelMapper.ts
- sdk/cards/src/internal/utils/ModelToJsonMapper.ts
- sdk/cards/src/model/CardInfo.ts
- sdk/cards/src/model/CardsData.ts
- sdk/cards/src/model/Widget.ts
- sdk/cards/src/model/enums/StaticImageType.ts
- sdk/core/android/build.gradle
- sdk/core/src/models/campaignsCore/MoEAccessibilityData.ts
- sdk/geofence/android/build.gradle
- sdk/inbox/android/build.gradle
- sdk/inbox/src/model/MoEMedia.ts
- sdk/inbox/src/utils/MoEInboxParser.ts
https://moengagetrial.atlassian.net/browse/MOEN-38838
Cards accessibility support
> MOEN-38838: Cards accessibility support

- sdk/cards/src/__mocks__/JsonDataProvider.ts
- sdk/cards/src/__mocks__/ModelClassProvider.ts
- sdk/cards/src/internal/utils/ModelToJsonMapper.ts
> MOEN-38838: Fixed compiling issue in test case of cards

- RELEASING.md
- sdk/cards/CHANGELOG.md
- sdk/cards/package.json
- sdk/geofence/CHANGELOG.md
- sdk/geofence/package.json
- sdk/inbox/CHANGELOG.md
- sdk/inbox/package.json
> MOEN-39455: Updated peer dependency `react-native-moengage` to `12.0.0`
